---
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
